import os
import json
from pathlib import Path



### COMMON
###--------------------------------------------------
SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = os.environ.get("DJANGO_DEBUG", True)

ALLOWED_HOSTS = json.loads(os.environ.get("ALLOWED_HOSTS", '["127.0.0.1", "0.0.0.0", "localhost"]'))

BASE_DIR = Path(__file__).resolve().parent.parent

APPS_DIR = BASE_DIR / "apps"

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'config.urls'


### APPS
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/ref/applications/#configuring-applications
###--------------------------------------------------
DJANGO_APPS = [
    # DJANGO APPS HERE
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # THIRD PARTY APPS HERE
    'rest_framework',
    'drf_spectacular',
    'debug_toolbar',
]

LOCAL_APPS = [
    # LOCAL APPS HERE
    'apps.users',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


### MIDDLEWARES
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/topics/http/middleware/#middleware
###--------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]


### DATABASE
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/ref/databases/#databases
###--------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DEFAULT_DB_NAME"),
        'USER': os.environ.get("DEFAULT_DB_USER"),
        'PASSWORD': os.environ.get("DEFAULT_DB_PASSWORD"),
        'HOST': os.environ.get("DEFAULT_DB_HOST"),
        'PORT': os.environ.get("DEFAULT_DB_PORT")
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


### DRF
###--------------------------------------------------
### https://www.django-rest-framework.org/api-guide/settings/#settings
###--------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication', # UNCOMMENT IF YOU USE BROWSABLEAPI
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        # 'rest_framework.renderers.BrowsableAPIRenderer', # UNCOMMENT IF YOU USE BROWSABLEAPI
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # SWAGGER
}


### SWAGGER
###--------------------------------------------------
### https://drf-spectacular.readthedocs.io/en/latest/settings.html#settings
###--------------------------------------------------
SPECTACULAR_SETTINGS = {
    "VERSION": "1.0.0",
    "TITLE": "Swagger API Documentations",
    "DESCRIPTION": "Automaticly generated by drf-spectacular",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SCHEMA_PATH_PREFIX_TRIM": "/api/",
}


### DJANGO-DEBUG-TOOLBAR
###--------------------------------------------------
### https://django-debug-toolbar.readthedocs.io/en/latest/
###--------------------------------------------------
DEBUG_TOOLBAR_CONFIG = {
    "DISABLE_PANELS": ["debug_toolbar.panels.redirects.RedirectsPanel"],
    "SHOW_TEMPLATE_CONTEXT": True,
}
### https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#configure-internal-ips
if DEBUG:
    import socket  # only if you haven't already imported this
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]


### TEMPLATES/STATIC
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/topics/templates/#configuration
### https://docs.djangoproject.com/en/4.2/howto/static-files/#configuring-static-files
###--------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = 'django_static/'


### PASSWORD VALIDATION
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/howto/static-files/#configuring-static-files
###--------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


### INTERNATIONALIZATION
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/topics/i18n/#internationalization-and-localization
###--------------------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


### TESTS
###--------------------------------------------------
### https://docs.djangoproject.com/en/4.2/topics/db/fixtures/#where-django-looks-for-fixtures
###--------------------------------------------------
FIXTURE_DIRS = [
    str(APPS_DIR / "fixtures"),
]
