name: Tests

env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  django-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        
      - name: Run django tests
        run: docker-compose run --rm drfs-django python manage.py test